export const imagesForProducts = [
    {
      id:"1",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712502515/Next/iphone11_ibxhb2.png",
    },
    {
      id:"2",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712502514/Next/mac-air_nbucpk.jpg",
    },
    {
      id:"3",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712503445/Next/ipad_qud0vh.jpg",
    },
    {
      id:"4",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712503557/Next/apple_watch_h1kynk.webp",
    },
    {
      id:"5",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712503610/Next/airpods_rrwltw.webp",
    },
    {
      id:"6",
      image:
        "https://res.cloudinary.com/dzxrc9b6o/image/upload/v1712503659/Next/homepod_jnqjbf.jpg",
    },
  ];